server:
  port: 8500
spring:
  application:
    name: purepicks-gateway
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 2
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.37.160:8848
    sentinel:
      transport:
        dashboard: 192.168.37.160:8858
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            # 控制允许的域名
            allowedOriginPatterns: "*"
            # 允许请求中携带的头信息
            allowedHeaders: "*"
            # 允许跨域请求的方式
            allowedMethods: "*"
            # 跨域检测的有效期,单位s
            maxAge: 36000
      routes:
        - id: server-product
          uri: lb://service-product
          predicates:
            - Path=/*/product/**
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/*/user/**
        - id: service-cart
          uri: lb://service-cart
          predicates:
            - Path=/api/*/cart/**
auth:
  blackList: "/api/**/auth/**"
