server:
  port: 8300
spring:
  application:
    name: service-cart
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.37.160:8848
    sentinel:
      transport:
        dashboard: 192.168.37.160:8858
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 2
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

knife4j:
  insight:
    enable: true
