server:
  port: 8100
spring:
  application:
    name: service-product
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/purepicks_manager?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: purepicks_manager_user
    password: devSurfer
    # HikariCP 配置项
    hikari:
      # 设置连接池的最大连接数，建议根据数据库的连接数限制进行调整
      maximum-pool-size: 20
      # 最小空闲连接数
      minimum-idle: 5
      # 连接池初始化连接数
      initialization-fail-timeout: 1
      # 最大等待时间（单位：毫秒），获取连接时，超时等待的最大时间 30秒
      connection-timeout: 30000
      # 连接测试查询语句
      connection-test-query: SELECT 1
      # 连接最大生命周期（单位：毫秒），超过最大生命周期的连接会被回收
      max-lifetime: 1800000
      # 空闲连接最大存活时间（单位：毫秒）
      idle-timeout: 600000
      # 是否自动提交事务
      auto-commit: true
      # 是否启用连接池性能统计
      pool-name: HikariCP
      # 连接泄漏检测时间（单位：毫秒），超过此时间未关闭的连接会被视为泄漏并抛出警告
      leak-detection-threshold: 2000
      # 是否使用数据库的连接验证机制，避免长时间没有使用连接而被数据库回收
      validation-timeout: 5000
  data:
    redis:
      host: 127.0.0.1
      database: 2
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.37.160:8848
        username: nacos
        password: nacos

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-prefix: devSurfer
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml

purepicks:
  minio:
    endpoint: 127.0.0.1
    port: 9000
    accessKey: YldujUvxicrZOHSOg1Vs
    secretKey: d5oqQCL2SPCpwGacuRSmkdxzN4rBR6MApdNhRd5x
    bucket: purepicks-manager-bucket
